version: '3.9'

services:
  django-server:
    container_name: django-server
    build: app/
    restart: always
    environment:
      - DEBUG=1
      - host_name=kht-test-apptrix.herokuapp.com
    ports:
      - "8000:8000"
      - "5432:5432"
    volumes:
      - ./app/:/app
    command: sh -c "gunicorn conf.wsgi --preload --timeout 10 --max-requests 1200"
