# Generated by Django 4.0.3 on 2022-03-12 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('from_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_from_client', to=settings.AUTH_USER_MODEL)),
                ('to_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_to_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
