# Generated by Django 4.0.3 on 2022-03-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_gender_alter_client_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date_time'], 'verbose_name': 'Симпатия', 'verbose_name_plural': 'Симпатий'},
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
